version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "fractal"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1092cddbjc88w"
s3_prefix = "fractal"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
