version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "demo-multiverse"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1opx9plsf7274"
s3_prefix = "demo-multiverse"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
