version: 0.2

env:
  variables:
    QUARKUS_PROFILE: "prod"
    MVN_XOPTS: "-B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn"
#    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"
#  parameter-store:
#    LOGIN_PASSWORD: /CodeBuild/dockerLoginPassword

phases:
  install:
    commands:
      - echo Install SDK and tools
      - curl -s "https://get.sdkman.io" | bash
      - source "/root/.sdkman/bin/sdkman-init.sh" && sdk install java 11.0.16-amzn && sdk install maven
      - npm install -g aws-cdk
#    finally:
#      - echo This always runs even if the update or install command fails 
  pre_build:
    commands:
      - echo Login before build
#      - docker login -u User -p $LOGIN_PASSWORD
  build:
    commands:
      - echo Build the packages
      - mvn -f src/demo-multiverse/pom.xml $MVN_XOPTS install
      - mvn -f src/demo-multiverse-sls/pom.xml $MVN_XOPTS install
      - mvn -f src/demo-multiverse-cdk/pom.xml $MVN_XOPTS install
      - cd src/demo-multiverse-cdk/ && cdk synth --all && find .
      - echo "build fs" && find .
  post_build:
    commands:
      - echo 'Deploy now. or later. idk :)'
#      - cd src/demo-multiverse-cdk/ && cdk deploy --all --require-approval=never
      - echo "post-build fs" && find .

#reports:
#  arn:aws:codebuild:your-region:your-aws-account-id:report-group/report-group-name-1:
#    files:
#      - "**/*"
#    base-directory: 'target/tests/reports'
#    discard-paths: no
#  reportGroupCucumberJson:
#    files:
#      - 'cucumber/target/cucumber-tests.xml'
#    discard-paths: yes
#    file-format: CUCUMBERJSON # default is JUNITXML
#artifacts:
#  files:
#    - target/messageUtil-1.0.jar
#  discard-paths: yes
#  secondary-artifacts:
#    artifact1:
#      files:
#        - target/artifact-1.0.jar
#      discard-paths: yes
#    artifact2:
#      files:
#        - target/artifact-2.0.jar
#      discard-paths: yes
cache:
  paths:
    - '/root/.m2/**/*'
